### ISSUE TITLE
Strong and Weak Transforms

### ISSUE THREAD

**Issue by yaldashbz** [CAMMA-public/HPE-AdaptOR#1]
Hi,

I couldn't find which transforms you used as strong and weak transforms for source and target datasets.
Could you please specify them?

Thanks.

**Comment by vinkle** [comment]
Hi, here is the data mapper class that applies the weak and strong transformations:
https://github.com/CAMMA-public/HPE-AdaptOR/blob/08a3b8b4a8ea80360ec3bb19afbeb4b9bb690653/adaptor/data/dataset_mapper_weak_strong.py#L185

settings for the transformations: https://github.com/CAMMA-public/HPE-AdaptOR/blob/08a3b8b4a8ea80360ec3bb19afbeb4b9bb690653/configs/base/Base_kmrcnn_R_50_FPN_3x_gn_amp_4gpus.yaml#L62
